name: OWASP Dependency Check

on:
    push:
        branches:
        - master

jobs:
    installNPM:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Install NPM dependencies
        run: |
          npm install --production --unsafe-perm
        
    depCheck:
      runs-on: ubuntu-latest
      steps:    
      - uses: sburris/dependency-check-action@master
        with:
          Project-Name: TestApp
    
    report:
      runs-on: ubuntu-latest
      steps:
      - name: Archive dependency check reports
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: reports


    