name: OWASP Dependency Check

on:
    push:
        branches:
        - master

jobs:
    depCheck:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Install NPM dependencies
        run: |
          npm install --production --unsafe-perm
        
      - uses: sburris/dependency-check-action@master
      - name: Scan dependency check
        with:
          Project-Name: TestApp

      - name: Archive dependency check reports
        uses: actions/upload-artifact@v1
        with:
          name: reports
          path: reports


    